### ISSUE TITLE
Expiration doesn't actually work

### ISSUE THREAD

**Issue by genewitch** [xanmanning/Knoxious-Open-Pastebin#23]
The only effect of expired pastes is a direct request, e.g. /index.php?134751

However, this does not expire the "raw" or "download" versions of the files.

For example, one uploads an image, and the expiry is 1 day. 24 hours later, the /index.php?134751 link says "paste expired!" but /index.php?134751@download will still download the image.

I am not sure if this project has been abandoned, and this bug could possibly be fixed with a cronjob that runs every default expiration time divided by 4, or 10, or whatever granularity you're looking for.

I'm currently fixing it by wiping the webroot and rsyncing a clean copy in, but this throws the good pastes out with the expired.

**Comment by xanmanning** [comment]
It does work, just doesn't check on raw or download.

fixed.
